### ISSUE TITLE
getting stuck at the locked door (my mistake they got locked out because of the bloody creates)

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#56] opened 2021-10-23 13:09 UTC
even after loading save they keep going until they hit the door

[0863 ariel stuck.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7403006/0863.ariel.stuck.zip)

![image](https://user-images.githubusercontent.com/91120787/138557598-a44ec11c-7c1e-460b-b6b7-18add1fdc888.png)

**Comment by IvanBajlo** [comment] 2021-10-23 13:11
and this one ended up stuck inside this space somehow... this game is getting really bizarre... sewers are really bad when it comes to pathfinding ;-)

![image](https://user-images.githubusercontent.com/91120787/138557745-604684d9-3dfe-4f76-9f74-bad005e85883.png)

**Comment by IvanBajlo** [comment] 2021-10-23 13:19
there are some stupid creates blocking path back... but still no idea how that gal teleported to that space and got stuck

**Comment by SerialKicked** [comment] 2021-10-23 13:45
Oki no problem, i'll just close and mark as a duplicate of #45 as there's already several issues about settlers getting stuck.

**Closed as completed by SerialKicked** 2021-10-23 13:45 UTC
Labels: ♾️ duplicate ♾️
